SELECT ROUND(
    SQRT(
        POWER((SELECT MIN(LAT_N) FROM STATION)-
               (SELECT MAX(LAT_N)FROM STATION),2)+
        POWER((SELECT MIN(LONG_W)  FROM STATION)-
              (SELECT MAX(LONG_W) FROM STATION),2)
    ),4);